### ISSUE TITLE
Add docker-compose config to getting started with docker

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/management-center-docs#176]
Regarding https://docs.hazelcast.com/management-center/latest/getting-started/get-started. 

I think it would be much easier for newcomers if we would have also a description of how to setup the hazelcast instance, to get the whole thing up and running. Or maybe include a simplistic docker-compose.yml to have a smoother user experience:

```yaml
version: "3.8"
services:
  hazelcast:
    image: hazelcast/hazelcast:5.1.1
    ports:
    - "5701:5701"
  management-center:
    image: hazelcast/management-center:5.1.3
    ports:
    - "8080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
```
