### ISSUE TITLE
Docs: Feedback for Get Started with Management Center Using Docker Compose

### ISSUE THREAD

**Issue by emreyigit** [hazelcast/management-center-docs#392]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/main/docs/modules/getting-started/pages/get-started.adoc)

Is there Hazelcast 5.6.0? In the docker compose file, MC and platform versions are same which is 5.6.0 but the latest platform is 5.5.2.

The docker compose from the doc:
```yaml
version: "3.8"
services:
  hazelcast:
    image: hazelcast/hazelcast:5.6.0
    ports:
    - "5701:5701"
  management-center:
    image: hazelcast/management-center:5.6.0
    ports:
    - "8080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
```
